name: CI-CD-Pipeline-to-AWS-ElastikBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "art-comp-application-packages"
  EB_APPLICATION_NAME       : "Myflask"
  EB_ENVIROMENT_NAME        : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  
  
on:
  push:
    branches:
      - master
      
jobs:
  my_ci:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Git clone
      uses: actions/checkout@v1
    
    - name: Create ZIP dep package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    
