name: CI-CD-Pipeline-to-AWS-ElastikBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "art-comp-application-packages"
  EB_APPLICATION_NAME       : "Myflask"
  EB_ENVIROMENT_NAME        : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  
  
on:
  push:
    branches:
      - master
      
jobs:
  my_ci:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Git clone
      uses: actions/checkout@v1
    
    - name: Create ZIP dep package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
    
    - name: Copy dep to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://#{{ EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print done message for CI finish
      run : echo "CI Pipline part finish successfully!"
